# Disabling sudo moves build to the Container Based Infrastructure on Travis CI
sudo: false

language: java
jdk: oraclejdk8

before_install:
  - pip install --user codecov
  - export ANDROID_HOME="$HOME"/android-sdk
  - mkdir -p "$ANDROID_HOME"
  - export ANDROID_SDK_FILE_NAME=sdk-tools-linux-3859397.zip
  - curl --fail https://dl.google.com/android/repository/$ANDROID_SDK_FILE_NAME --silent --location --output $ANDROID_SDK_FILE_NAME
  - unzip -qq $ANDROID_SDK_FILE_NAME -d "$ANDROID_HOME"
  - rm $ANDROID_SDK_FILE_NAME
  - export ANDROID_SDK_INSTALL_COMPONENT="echo \"y\" | \"$ANDROID_HOME\"/tools/bin/sdkmanager > /dev/null"
  - eval $ANDROID_SDK_INSTALL_COMPONENT '"tools"'
  - eval $ANDROID_SDK_INSTALL_COMPONENT '"platform-tools"'
  - eval $ANDROID_SDK_INSTALL_COMPONENT '"build-tools;26.0.2"'
  - eval $ANDROID_SDK_INSTALL_COMPONENT '"platforms;android-23"'
  - eval $ANDROID_SDK_INSTALL_COMPONENT '"extras;android;m2repository"'
  - eval $ANDROID_SDK_INSTALL_COMPONENT '"extras;google;m2repository"'

install:
  - echo 'Just overriding standard Travis install procedure to avoid unnecessary work.'

script:
  - ./build.sh
  
after_success:
  - codecov

notifications:
  email: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
